Optimizer filebeat config
wangy1931/tcollector pull request #43
Opened 2017-08-15 02:13 UTC by IamAScholar

1，cpu添加对多核的分辨
2，优化filebeat的配置

2017-08-15 04:32 UTC, wangy1931 requested changes

2017-08-15 04:32 UTC, wangy1931 commented on collectors/builtin/top_n.py
> +                raise CalledProcessError(retval, "ps -Ao comm,pid,%s,cmd --sort=-%s | head -n %s"%(ps_field, ps_sort_by,self.N), "ps returned code %i" % retval)
这里可以直接log_exception, return, 可以不要raise

2017-08-15 04:32 UTC, wangy1931 commented on deploy/filebeat_conf.py
> +def get_user_conf_dict(config,config_name):
这个是把user.conf 格式从python 转成简单的key=value 格式吗？如果是，如何做向后兼容？

2017-08-18 09:43 UTC, IamAScholar commented on deploy/filebeat_conf.py
> +def get_user_conf_dict(config,config_name):
现在可以往后兼容了

2017-08-18 09:44 UTC, IamAScholar commented on collectors/builtin/top_n.py
> +                raise CalledProcessError(retval, "ps -Ao comm,pid,%s,cmd --sort=-%s | head -n %s"%(ps_field, ps_sort_by,self.N), "ps returned code %i" % retval)
这里的处理是，先raise再try exception,这里可能有两个exception

2017-08-18 09:49 UTC, IamAScholar commented on collectors/builtin/top_n.py
> +                raise CalledProcessError(retval, "ps -Ao comm,pid,%s,cmd --sort=-%s | head -n %s"%(ps_field, ps_sort_by,self.N), "ps returned code %i" % retval)
在try exception 里面有return 和日志打印

2017-08-18 10:37 UTC, merged

2017-08-20 00:24 UTC, wangy1931 reviewed
OK, looks good